###
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "name" : "Student 1",
    "lastname":"Lastaname1",
    "age":19,
    "email":"student@ucaldas.edu.co"
}

###
GET http://localhost:3000/api/users HTTP/1.1

###
GET http://localhost:3000/api/users/6213bb15259ee865d32bf11f HTTP/1.1

###
DELETE http://localhost:3000/api/users/6213bb15259ee865d32bf11f HTTP/1.1

###
PUT http://localhost:3000/api/users/6213bb15259ee865d32bf11f HTTP/1.1
Content-Type: application/json

{
    "name": "luis",
    "lastname": "ramirez",
    "age": 12,
    "email": "luis@gmail.com"
}
